apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: my-app-container
          image: "$(MY_APP_IMAGE)"
          ports:
            - containerPort: 80
          env:
            - name: MY_APP_IMAGE
              valueFrom:
                configMapKeyRef:
                  name: my-app-config
                  key: image
